- name: OS Pre-reqs
  include_role:
    name: common
    tasks_from: os-prereqs

- name: Setup Yum Repos
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: installed


- name: Install Redis
  yum:
    name: redis
    state: installed
    enablerepo: remi




  # yum install epel-release yum-utils -y
  # yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
  # yum-config-manager --enable remi
  # yum install redis -y
#Update the BindIP from 127.0.0.1 to 0.0.0.0 in config file /etc/redis.conf
#
#Start Redis Database

# systemctl enable redis
# systemctl start redis