- name: Demo of vars on Play level
  hosts: all
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print Variable Value
      debug:
        msg: Hello {{ URL_PLAY }}

    - name: Print Variable again
      debug:
        msg: Bye {{ URL_PLAY }}

## If you declare a variable in play level then you can access the value across the play tasks.

- name: Demo on vars on Task level
  hosts: all
  tasks:
    - name: print task level variable
      debug:
        msg: Hello {{ URL_TASK1 }}
      vars:
        URL_TASK1: task1.example.com

    - name: print task level variable
      debug:
        msg: Hello again {{ URL_PLAY }}

## Tasks level variables are going have the scope to the only task on where it is declared.