- name: Demo on conditions
  hosts: all
  vars:
    A: 100
    INSTALL: true
  tasks:
    - name: Condition on strings
      debug:
        msg: Condition on strings
      when: APP == "frontend"


    - name: Condition on Numbers
      debug:
        msg: Condition on Numbers
      #when: A == 101
      when: A >= 50

    - name: Conditions on booleans
      debug:
        msg: Conditions on booleans
      when: INSTALL | bool

    - name: Get stats of a file
      stat:
        path: /etc/passwd
      register: st

    - name: Print Out
      debug:
        msg: "{{st}}"

    - name: /etc/passwd is writable
      debug:
        msg: /etc/passwd is writable
      when: st.stat.writable | bool




