- name: Install Nginx
  yum:
   name: nginx
   state: installed
   # yum install nginx -y

 - name: Remove Html Docs
   file:
     path: /usr/share/nginx/html
     state: absent
     # cd /usr/share/nginx/html
     # rm -rf *


- name: Download from Github
  include_role:
    name: common
    tasks_from: download-github
# curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
# unzip /tmp/frontend.zip



- name: Start Nginx Service
  systemd:
    name: nginx
    state: restarted
    enabled: yes
# systemctl enable nginx
# systemctl start nginx
#systemctl restart nginx



