


 # os pre-reqs

- name: OS Pre-reqs
  include_role:
    name: common
    tasks_from: os-prereqs

# Setup MySQL Repo

- name: Setup Yum repos for Mysql
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

# Install MySQL
# yum remove mariadb-libs -y

- name: Remove MariaDB libs
  yum:
    name: mariadb-libs
    state: absent

# yum install mysql-community-server -y

- name: Install MySQL Server
  yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

# Start mysql

- name: Start MySQL
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check if MySQL password is set or not
  mysql_info:
    login_user: "root"
    login_password: "RoboShop@123"
    filter: version
  ignore_errors: yes
  register: out

- name: Resetting the Default password
  when: out.failed | bool
  block:
    - name: Grab default Password
      shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: DPASS

    - name: copy password reset SQL file
      copy:
        src: reset-password.sql
        dest: /tmp

    - name: Reset the Password
      shell: mysql --connect-expired-password -u root -p"{{ DPASS.stdout }}" </tmp/reset-password.sql


- name: Download from Github
  include_role:
    name: common
    tasks_from: download-github


- name: Load Schema
  shell: mysql -u root -p'RoboShop@123'  <shipping.sql
  args:
    chdir: /tmp/mysql-main















